
# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /finalapp

# Copy the current directory contents into the container at /app
COPY . /finalapp
RUN pip uninstall -y openai

# Install the necessary libraries
RUN pip install --no-cache-dir PyMuPDF openai==0.28 streamlit

# Expose the port that Streamlit will run on
EXPOSE 8506


# Command to run the Streamlit app
CMD ["streamlit", "run", "finalapp.py", "--server.port=8506"]

